name: Docker Image CI

on:
  push:
    branches:
    - master

jobs:  
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build, Tag, Push
      uses: mattdavis0351/actions/docker-gpr@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        image-name: thunderdome-planning-poker
#     - name: Publish to Github Registry
#       uses: elgohr/Publish-Docker-Github-Action@master
#       with:
#         name: docker.pkg.github.com/stevenweathers/thunderdome-planning-poker/thunderdome-planning-poker
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}
#         registry: docker.pkg.github.com
